### ISSUE TITLE
[FR] Add a button to enter HACS

### ISSUE THREAD

**Issue by mase60** [dwainscheeren/lovelace-dwains-theme#10]
Having a button in, for example, house data to enter HACS to update plugins would be a nice idea in my opinion.

**Comment by nexro567** [comment]
Fix it by yourself?

Update your `house_data.yaml` in your config of HA `config/dwains-theme/views/main/more-pag_page/house_data.yaml`

Add in the footer of that item this code:

>               - type: custom:button-card
>                template: more_page_list-item
>                name: HACS update
>                tap_action: 
>                  action: navigate
>                  navigation_path: /hacs

After that you need to click on the three dots on right side of your screen and click `UPGRADE ALL`.

**Comment by dwainscheeren** [comment]
@nexro567 I would advise against adapting core files of my theme, because future updates will overwrite this changes you made.

@mase60 I believe you mostly want this for the mobile app, because the sidebar is there disabled? In the next version the sidebar will be working again on mobile HA so you can access HACS from there.

**Comment by mase60** [comment]
thanks, this is exactly what i was looking for. guess it´s good as a workaround until we get the next version with the sidebar.
