### ISSUE TITLE
[FR] Divide rooms into floor levels

### ISSUE THREAD

**Issue by kbrigitta** [dwainscheeren/lovelace-dwains-theme#18]
Hi,
It would be nice if the rooms could be into floor levels.
For example:
GROUND FLOOR:
   Entrance
   Office
   Living Room
FIRST FLOOR:
   Master Bedroom
   Bathroom

**Comment by dwainscheeren** [comment]
I'm not sure this would be handy. How do you see this implemented in your mind?

**Comment by mwbehr1** [comment]
Just to chime in (rather than make a new request), I think it might be handy to have the ability to have "nested" rooms. My original thought would be to have bathrooms or closets as "sub-rooms" to main rooms. However, that same concept could be utilized by someone wanting to group by floors or wings.

From an implementation standpoint, I would think the main room would inherit all of the devices and sensors from the sub-rooms on the main tag. When opening the main room, however, you'd only see the individual devices and sensors for that main room, and a new tag (or tags) of the sub-room(s) with the remaining devices and sensors.

Just a thought.

**Comment by dwainscheeren** [comment]
I personally don't see any advantage on using subrooms or nested rooms. I need to completely rewrite and refactor the way the theme works then.

**Comment by mwbehr1** [comment]
Understood. I certainly don't see enough benefit to warrant that kind of effort. Thanks for the response.

**Comment by dwainscheeren** [comment]
Maybe in the future, I will keep it in mind.
