### ISSUE TITLE
[FR] more icons on the rooms homepage

### ISSUE THREAD

**Issue by Nic0205** [dwainscheeren/lovelace-dwains-theme#25]
On the rooms homepage there is a dynamic icon for windows - it would be great if

a) the dynamic window icon would be customizable. For me it would be great if the icon is always there and only if the window is open it should be hilighted. At the moment the icon only appears if a window is open but not all the time.

b) further icons for e.g. covers could be set like described at a).

I hope I was detailed enough - if not just ask ;-)

**Comment by dwainscheeren** [comment]
a) uhm you can override each icon to your own one with `icons.yaml`. Regarding the show of the icons on the homepage room buttons I did only show the light button always, by design choose wise. If I add all buttons and make them grey its quit looks messy and busy on the homepage. And I only want to know if something is on in a room. I maybe add a function in the future that you can set a variable to true to always show the icons even when they are off. 
Regarding the problem that you don't always see when a window is open I think this has to do something with your entity please check if it states works.

b) What do you mean with this?

**Comment by Nic0205** [comment]
for a): this function would be really great - perhaps it could be implemented for each entitiy-type. I mean that everyone could decide himself if for example the icon for windows or for lights is shown all the time and so it would be the responsibility of the user to get it not messy.

for b):  i want to know if the cover in a room is up or down - for that i would like to see it in the homepage icon

**Comment by Brausmith** [comment]
To further point b), I would like an icon to show if the room's thermostat is off/cooling/heating.
![2020-03-02 19_19_37-Home Assistant](https://user-images.githubusercontent.com/3722950/75662485-e8586100-5cba-11ea-8849-3f9301aba698.png)

**Comment by dwainscheeren** [comment]
This is already next to the temperature if its heating with an radiator icon

**Comment by Brausmith** [comment]
Ah, I see. Maybe if the same could be done for cooling?
I live in a warm climate where cooling is mostly used.

**Comment by dwainscheeren** [comment]
In 1.3.1 you also see cooling etc in the homepage icons.
