### ISSUE TITLE
[FR] Toggling lights single tap

### ISSUE THREAD

**Issue by greetoz** [dwainscheeren/lovelace-dwains-theme#58]
The way to toggle lights is not user friendly or logical. This should be customizable or switched around. As you would normally open the app to toggle a light, the on/off should be under the single tap. The double tap should open the more options page. The current config just introduces unnecessary tapping as most people would not want to change the light options everytime but just want to switch the light.

**Comment by dwainscheeren** [comment]
The reason I choose to use double tap on buttons to toggle them is because I otherwise don't had a 1 equal way in the whole theme. For example on the homepage if you double tap a room it toggles all the lights inside that room. If you go inside a room and double tap the lights button it also toggles all lights, so for me when I enter the lights page of a room I also suspect a double tap will toggle a light there too. Also this is sort of duplicate of #8

**Comment by dwainscheeren** [comment]
Also do you mostly toggle lights on the all lights page or inside a lights page of a room? And do you toggle mostly a complete room or single lights inside a room? Thanks.

**Comment by greetoz** [comment]
I still think its not logical... double tap should do something more. 

This is also the case with toggling all lights (as its a double tap that does something more (toggle all lights), and single tap opens the menu). 

That more people are asking how to toggle lights also shows its not the way people assume it would work. Maybe from a programming standpoint its logical to do it this way but from a user standpoint its weird. I can live with double tapping all lights in a room but i mostly toggle single lights. (switch a light on or off if i want something different then an automation did).

It it possible to change this in your config myself? If not this is a no go option for me at least. And yes its a sort of dupe from the other issue.. but thats a question how to do it.. not to change it.

**Comment by dwainscheeren** [comment]
Yeah I was already looking into this before because of some other questions. I still want to keep the double tap on some places. But maybe on the All lights page and on the Lights page inside a room a single tap on the lights would toggle it and a hold action or double tap will bring up the popup to change the light (brightness etc). If I change it like this in the next update would it fit your needs?

**Comment by greetoz** [comment]
Yes that would be great. But I understand thats its your theme. I dont want to force anything. But that would work great for me at least ;-).

**Comment by clfregis** [comment]
Well, in my case I did that change, because the users in my house were complaining about that. You can do that @greetoz . But, if it serves as a suggestion, I would suggest to change that option. In my case I left the double tap on main menu, but, once in a room page, single tap toggles the lights.

**Comment by greetoz** [comment]
This has been resolved in 1.3.x! I'll close the issue.
